version: '3.8'
services:
  imdb_scrapper:
    image: 'imdb_scrapper'
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - "C:/Users/USER/docker_test:/imdb_scrapper/database"
volumes:
    imdb_scrapper: